USE tpi_pedido_envio; -- Seleccionamos el esquema

INSERT INTO LOCALIDADES (provincia, ciudad, codigo_postal) VALUES
('Ciudad Autónoma de Buenos Aires', 'Buenos Aires', 'C1000'),
('Ciudad Autónoma de Buenos Aires', 'Belgrano', 'C1428'),
('Buenos Aires', 'La Plata', 'B1900'),
('Buenos Aires', 'Mar del Plata', 'B7600'),
('Catamarca', 'San Fernando del Valle de Catamarca', 'K4700'),
('Catamarca', 'Andalgalá', 'K4740'),
('Chaco', 'Resistencia', 'H3500'),
('Chaco', 'Presidencia Roque Sáenz Peña', 'H3700'),
('Chubut', 'Rawson', 'U9103'),
('Chubut', 'Comodoro Rivadavia', 'U9000'),
('Córdoba', 'Córdoba', 'X5000'),
('Córdoba', 'Río Cuarto', 'X5800'),
('Corrientes', 'Corrientes', 'W3400'),
('Corrientes', 'Goya', 'W3450'),
('Entre Ríos', 'Paraná', 'E3100'),
('Entre Ríos', 'Concordia', 'E3200'),
('Formosa', 'Formosa', 'P3600'),
('Formosa', 'Clorinda', 'P3610'),
('Jujuy', 'San Salvador de Jujuy', 'Y4600'),
('Jujuy', 'Libertador General San Martín', 'Y4512'),
('La Pampa', 'Santa Rosa', 'L6300'),
('La Pampa', 'General Pico', 'L6360'),
('La Rioja', 'La Rioja', 'F5300'),
('La Rioja', 'Chilecito', 'F5360'),
('Mendoza', 'Mendoza', 'M5500'),
('Mendoza', 'San Rafael', 'M5600'),
('Misiones', 'Posadas', 'N3300'),
('Misiones', 'Iguazú', 'N3370'),
('Neuquén', 'Neuquén', 'Q8300'),
('Neuquén', 'San Martín de los Andes', 'Q8370'),
('Río Negro', 'Viedma', 'R8500'),
('Río Negro', 'San Carlos de Bariloche', 'R8400'),
('Salta', 'Salta', 'A4400'),
('Salta', 'San Ramón de la Nueva Orán', 'A4530'),
('San Juan', 'San Juan', 'J5400'),
('San Juan', 'Caucete', 'J5442'),
('San Luis', 'San Luis', 'D5700'),
('San Luis', 'Villa Mercedes', 'D5730'),
('Santa Cruz', 'Río Gallegos', 'Z9400'),
('Santa Cruz', 'Caleta Olivia', 'Z9011'),
('Santa Fe', 'Santa Fe', 'S3000'),
('Santa Fe', 'Rosario', 'S2000'),
('Santiago del Estero', 'Santiago del Estero', 'G4200'),
('Santiago del Estero', 'La Banda', 'G4300'),
('Tierra del Fuego', 'Ushuaia', 'V9410'),
('Tierra del Fuego', 'Río Grande', 'V9420'),
('Tucumán', 'San Miguel de Tucumán', 'T4000'),
('Tucumán', 'Yerba Buena', 'T4107');
