START TRANSACTION;

-- 🔢 generador de números 1..150000 (sin CTE)
-- usa 6 "tablas dígito" para llegar cómodo a 1,000,000 y luego limita a 150k
INSERT INTO PEDIDO (id_cliente, fecha_pedido, estado_pedido, total, observaciones)
SELECT
  c.id_cliente,
  DATE_SUB(NOW(), INTERVAL FLOOR(RAND()*365) DAY) AS fecha_pedido,
  CASE
    WHEN RAND() < 0.15 THEN 'Pendiente'
    WHEN RAND() < 0.35 THEN 'Confirmado'
    WHEN RAND() < 0.55 THEN 'En Preparacion'
    WHEN RAND() < 0.75 THEN 'Despachado'
    WHEN RAND() < 0.92 THEN 'Entregado'
    ELSE 'Cancelado'
  END AS estado_pedido,
  0.00 AS total,                -- luego lo actualizás con el paso 6
  NULL AS observaciones
FROM (
  SELECT 
    a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 + f.N*100000 + 1 AS n
  FROM (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
) gen
JOIN (SELECT COUNT(*) AS cnt FROM CLIENTE) tot
JOIN (
  -- barajamos clientes UNA sola vez sin window functions (compatible 5.7/MariaDB)
  SELECT x.id_cliente, (@rn:=@rn+1) AS rn
  FROM (SELECT id_cliente FROM CLIENTE ORDER BY RAND()) x
  CROSS JOIN (SELECT @rn:=0) vars
) c
  ON ((gen.n - 1) % tot.cnt) + 1 = c.rn
WHERE gen.n <= 150000;   -- límite real

COMMIT;
