START TRANSACTION;

-- Generador de números 1..30000 sin usar WITH RECURSIVE
INSERT INTO CLIENTE (cliente_nombre, cliente_email, cliente_telefono, direccion_entrega, id_localidad)
SELECT
  CONCAT('Cliente ', gen.n) AS cliente_nombre,
  CONCAT('cliente', gen.n, '@mail.test') AS cliente_email,
  CONCAT('+54-9-11-', LPAD(gen.n % 10000, 4, '0'), '-', LPAD((gen.n*7)%10000, 4, '0')) AS cliente_telefono,
  CONCAT('Calle ', (gen.n % 3000) + 1, ' #', (gen.n*13)%9000) AS direccion_entrega,
  l.id_localidad
FROM (
  SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 + 1 AS n
  FROM (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
        UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
              UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
) AS gen
JOIN (
  SELECT id_localidad,
         ROW_NUMBER() OVER (ORDER BY id_localidad) AS rn,
         COUNT(*) OVER () AS cnt
  FROM LOCALIDADES
) l
  ON ((gen.n - 1) % l.cnt) + 1 = l.rn
WHERE gen.n <= 30000;

COMMIT;
